# CUDA_VISIBLE_DEVICES=4,5,6,7 python ./tools/art_test.py /home/data1/sxg/IC19/mmdetection-master/configs/art_crop/mask_rcnn_r50_fpn_1x_ic17_msda_shortv3.py /home/data1/sxg/IC19/mmdetection-master/work_dirs/art_crop_mrcnn_r50_test_msda_e/epoch_24.pth /home/data1/sxg/IC19/mmdetection-master/configs/evaluation/art_crop/art_eval_setting.json --gpus 4 --save_json /home/data1/sxg/IC19/mmdetection-master/submit/art/submit.json --show_path /home/data1/sxg/IC19/mmdetection-master/visualization/eval_result/art/ --show

# CUDA_VISIBLE_DEVICES=4,5,6,7 python ./tools/art_test.py /home/data1/sxg/IC19/mmdetection-master/configs/art/mask_rcnn_r50_fpn_1x_ic17_dice.py /home/data1/sxg/IC19/mmdetection-master/work_dirs/art_mrcnn_r50_test_dice_a/epoch_24.pth /home/data1/sxg/IC19/mmdetection-master/configs/evaluation/art/art_eval_setting.json --gpus 4 --save_json /home/data1/sxg/IC19/mmdetection-master/submit/art/submit.json --show_path /home/data1/sxg/IC19/mmdetection-master/visualization/eval_result/art/ --show

# CUDA_VISIBLE_DEVICES=0,1,2,3 python ./tools/art_test.py /home/data1/sxg/IC19/mmdetection-master/configs/art/mask_rcnn_r50_fpn_2x_gn_ic17_deepHead.py /home/data1/sxg/IC19/mmdetection-master/work_dirs/art_mrcnn_r50_test_deepHead_c/epoch_22.pth /home/data1/sxg/IC19/mmdetection-master/configs/evaluation/art/art_eval_setting.json --gpus 4 --save_json /home/data1/sxg/IC19/mmdetection-master/submit/art/submit.json --show_path /home/data1/sxg/IC19/mmdetection-master/visualization/eval_result/art/ --show

# CUDA_VISIBLE_DEVICES=4,5,6,7 python ./tools/art_test.py /home/data1/sxg/IC19/mmdetection-master/configs/art/mask_rcnn_r50_fpn_1x_ic17_2xmask.py /home/data1/sxg/IC19/mmdetection-master/work_dirs/art_mrcnn_r50_test_2xmask_b/epoch_24.pth /home/data1/sxg/IC19/mmdetection-master/configs/evaluation/art/art_eval_setting.json --gpus 4 --save_json /home/data1/sxg/IC19/mmdetection-master/submit/art/submit.json --show_path /home/data1/sxg/IC19/mmdetection-master/visualization/eval_result/art/ --show

# CUDA_VISIBLE_DEVICES=4,5,6,7 python ./tools/art_test.py /home/data1/sxg/IC19/mmdetection-master/configs/art_crop/mask_rcnn_r50_fpn_1x_ic17_multiroiextractor_msda.py /home/data1/sxg/IC19/mmdetection-master/work_dirs/art_crop_mrcnn_r50_fpn_1x_ic17_multiroiextractor_msda_a/epoch_24.pth /home/data1/sxg/IC19/mmdetection-master/configs/evaluation/art_crop/art_eval_setting.json --gpus 4 --save_json /home/data1/sxg/IC19/mmdetection-master/submit/art/submit.json --show_path /home/data1/sxg/IC19/mmdetection-master/visualization/eval_result/art/ --show

# CUDA_VISIBLE_DEVICES=0,1,2,3 python ./tools/art_test.py /home/data1/sxg/IC19/mmdetection-master/configs/art_crop/mask_rcnn_r50_fpn_1x_ic17_PMTD_msda.py  /home/data1/sxg/IC19/mmdetection-master/work_dirs/art_crop_mrcnn_r50_fpn_1x_ic17_PMTD_msda_a/epoch_24.pth /home/data1/sxg/IC19/mmdetection-master/configs/evaluation/art_crop/art_eval_setting.json --gpus 4 --save_json /home/data1/sxg/IC19/mmdetection-master/submit/art/submit.json --show_path /home/data1/sxg/IC19/mmdetection-master/visualization/eval_result/art/ --show

# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python ./tools/art_test.py /home/data1/sxg/IC19/mmdetection-master/configs/art_crop/mask_rcnn_r50_fpn_1x_ic17_msda.py /home/data1/sxg/IC19/mmdetection-master/work_dirs/art_crop_mrcnn_r50_test_msda_b/epoch_24.pth /home/data1/sxg/IC19/mmdetection-master/configs/evaluation/art_crop/art_eval_setting.json --gpus 8 --save_json /home/data1/sxg/IC19/mmdetection-master/submit/art/submit.json --show_path /home/data1/sxg/IC19/mmdetection-master/visualization/eval_result/art/ --show

# CUDA_VISIBLE_DEVICES=4,5,6,7 python ./tools/art_test.py /home/data1/sxg/IC19/mmdetection-master/configs/art_crop/mask_rcnn_r50_fpn_1x_ic17_msda_pan.py /home/data1/sxg/IC19/mmdetection-master/work_dirs/art_crop_mrcnn_r50_fpn_1x_ic17_msda_pan_rerun/epoch_23.pth /home/data1/sxg/IC19/mmdetection-master/configs/evaluation/art_crop/art_eval_setting.json --gpus 3 --save_json /home/data1/sxg/IC19/mmdetection-master/submit/art/submit.json --show_path /home/data1/sxg/IC19/mmdetection-master/visualization/eval_result/art/ --show

# CUDA_VISIBLE_DEVICES=4,5,6,7,0,1,2,3 python ./tools/art_test.py /home/data1/sxg/IC19/mmdetection-master/configs/art_crop/mask_rcnn_r50_fpn_1x_ic17_msda_deepan.py /home/data1/sxg/IC19/mmdetection-master/work_dirs/art_crop_mrcnn_r50_fpn_1x_ic17_msda_deepan_a/epoch_23.pth /home/data1/sxg/IC19/mmdetection-master/configs/evaluation/art_crop/art_eval_setting.json --gpus 8 --save_json /home/data1/sxg/IC19/mmdetection-master/submit/art/submit.json --show_path /home/data1/sxg/IC19/mmdetection-master/visualization/eval_result/art/ --show

# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python ./tools/art_test.py /home/data1/sxg/IC19/mmdetection-master/configs/art_crop/mask_rcnn_r50_fpn_1x_ic17_msda.py /home/data1/sxg/IC19/mmdetection-master/work_dirs/art_crop_mrcnn_r50_fpn_1x_ic17_msda_rerun/epoch_24.pth /home/data1/sxg/IC19/mmdetection-master/configs/evaluation/art_crop/art_eval_setting.json --gpus 8 --save_json /home/data1/sxg/IC19/mmdetection-master/submit/art/submit.json --show_path /home/data1/sxg/IC19/mmdetection-master/visualization/eval_result/art/ --show


# CUDA_VISIBLE_DEVICES=2,5 python ./tools/art_test.py /home/data1/sxg/IC19/mmdetection-master/configs/art_crop/mask_rcnn_r50_fpn_1x_ic17_msda_2xepochs.py /home/data1/sxg/IC19/mmdetection-master/work_dirs/art_crop_mrcnn_r50_test_msda_2xepoch_a/epoch_45.pth /home/data1/sxg/IC19/mmdetection-master/configs/evaluation/art_crop/art_eval_setting.json --gpus 2 --save_json /home/data1/sxg/IC19/mmdetection-master/submit/art/submit.json --show_path /home/data1/sxg/IC19/mmdetection-master/visualization/eval_result/art/ --show

# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python ./tools/art_test.py /home/data1/sxg/IC19/mmdetection-master/configs/art_crop/mask_rcnn_r50_fpn_2x_ic17_msda_pan.py /home/data1/sxg/IC19/mmdetection-master/work_dirs/art_crop_mrcnn_r50_fpn_2x_ic17_msda_pan_a/epoch_46.pth /home/data1/sxg/IC19/mmdetection-master/configs/evaluation/art_crop/art_eval_setting.json --gpus 8 --save_json /home/data1/sxg/IC19/mmdetection-master/submit/art/submit.json --show_path /home/data1/sxg/IC19/mmdetection-master/visualization/eval_result/art/ --show

CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python ./tools/art_test.py /home/data1/sxg/IC19/mmdetection-master/configs/art_crop/mask_rcnn_r50_fpn_2x_ic17_msda_2xanchorscales.py /home/data1/sxg/IC19/mmdetection-master/work_dirs/art_crop_mrcnn_r50_fpn_2x_ic17_msda_2xanchorscales_b/epoch_48.pth /home/data1/sxg/IC19/mmdetection-master/configs/evaluation/art_crop/art_eval_setting.json --gpus 8 --save_json /home/data1/sxg/IC19/mmdetection-master/submit/art/submit.json --show_path /home/data1/sxg/IC19/mmdetection-master/visualization/eval_result/art/ --show
